### ISSUE TITLE
Carthage Error

### ISSUE THREAD

**Issue by inPhilly** [kingiol/KDInteractiveNavigationController#8]
*** Skipped building AHKNavigationController due to the error:
Dependency "AHKNavigationController" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/kingiol/AHKNavigationController/issues/new

**Comment by inPhilly** [comment]
Neither AHKNavigationController nor KDInteractiveNavigationController work in Carthage.

**Comment by kingiol** [comment]
Now fixed, Thx.
